name: Copilot Swift PR Actions
description: Collection of PR Actions geared mostly towards iOS projects

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - --github-token=${{ inputs.GITHUB_TOKEN }}
